import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/context/theme-provider';
import { Toaster } from '@/components/ui/sonner';
import QueryProvider from '@/context/query-provider';

const dm_sans = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Squeezy',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			suppressHydrationWarning>
			<body className={`antialiased bg-background ${dm_sans.className} `}>
				<QueryProvider>
					<ThemeProvider
						attribute='class'
						defaultTheme='light'
						enableSystem={false}
						disableTransitionOnChange>
						{children}
						<Toaster
							position='top-right'
							toastOptions={{
								classNames: {
									error: 'bg-red-600 text-white',
									success: 'bg-green-600 text-white',
									warning: 'bg-yellow-500 text-black',
								},
							}}
						/>
					</ThemeProvider>{' '}
				</QueryProvider>
			</body>
		</html>
	);
}
